[package]
name = "conspiracy"
version = "0.1.0"
authors = ["Rodrigo Oliveira <rodrigo.redcode@gmail.com>"]
edition = "2018"

[features]
default = []
vulkan = ["amethyst/vulkan"]

[dependencies]
amethyst = {path="amethyst", features=["ui"]}
